Messages:
  Prefix: '&8[&2Splegg&r-&4OG&7] &3'
  NoPermission: '&cYou do not have permission!'
  JoinGame: '&8[&a%count%/%maxcount%&8] &6%player% has joined the game.'
  LeaveGame: '&6You have left the lobby for map &c%map%'
  LobbyTimer: '&6Match starting &f%timer% &6seconds.'
  InstructionsGame: '&6Use the shovel to throw eggs and make the other players fall!'
  GraceTimeStart: '&6Grace Period (&f%grace%&6s)'
  GraceTimeFinish: '&6Grace Period Over!'
  EndingTimer: '&6Game is ending in &f%timer%'
  Youbrokeblocks: '&6You broke %broke% blocks.'
  KnockoutPlayer: '&6Player %player% was eliminated from the game.'
  PlayersRemaining: '&e&l%count% players remain alive.'
  AlreadyInGame: '&6You are already in a game.'
  AlreadyInLobby: '&6You are already in this lobby.'
  NoEnoughMoney: '&cYou dont have enough &BDiamonds &cto purchase this shovel.!'
  NoEnoughPlayers: '&cThere are not enough players to start the game.'
  NotBreakSign: '&6You cannot break a splegg sign!'
  RemovedSign: '&6Removed a splegg sign for map &c%map%'
  CreateSign: '&6You have created a splegg sign for: &b%map%'
  Timelimitreached: '&6Time limit reached.'
  Mapnotexist: '&cMap does not exist!'
  Mapdisabled: '&4Map is disabled.'
  Haveyoueverbought: '&cYou already own this shovel.'
  BuyGoldShovel: '&BYou bought a Gold Shovel!'
  BuyDiamondShovel: '&BYou bought a Diamond Shovel!'
  VIPPrivilege: '&6Only &fOG &6players and above can enter the full game!'
  VIPJoinGame: '&6You have joined a full game thanks to your donor rank. Thank you for supporting &2True&4OG!'
Scoreboard:
  Title: '&2Splegg&r-&4OG'
  Queue: '&6Players Waiting:'
  Starting: '&6Starting in:'
  BrokenBlocks: '&eBlocks Broken:'
Money:
  KillPlayer: 0
  FinishGame: 1
Options:
  Timer: 120
  AutoStartPlayers: 4
  GraceTime: 10
Sings:
  Format:
    1: '&8[&2Splegg&r-&4OG&8]'
    2: '%status%'
    3: '%map%'
    4: '&5%count%/%maxcount%'
  Restarting:
    1: '###########################'
    2: '&8[&6Restarting &2Splegg&4OG&8]'
    3: '%map%'
    4: '###########################'
  Status:
    Join: '&4[Join]'
    Started: '&6[Started]'
    Disabled: '&4[Disabled]'
Shovels:
  Iron:
    Name: '&f&lIron Shovel'
    Lore: '&e&lClick right to launch eggs!'
  Gold:
    Name: '&e&lGolden Shovel'
    Lore: '&e&lClick right to launch eggs!'
  Diamond:
    Name: '&b&lDiamond Shovel'
    Lore: '&e&lClick right to launch eggs!'
GUI:
  Shop:
    Title: '&lSplegg Shop'
    Size: 9
    GoldShovel:
      Name: '&e&lGolden Shovel'
      Description: '&6The Golden Shovel shoots 2 eggs at a time! Price: &B%price% Diamonds'
      Price: 500
    DiamondShovel:
      Name: '&b&lDiamond Shovel'
      Description: '&6The Diamond Shovel shoots 3 eggs at a time! Price: &B%price% Diamonds'
      Price: 1000
Shop:
  Item: DIAMOND
  Slot: 1
  Name: 'Splegg Shop'
  Lore: '&eBuy fancy new shovels!'