Messages:
  Prefix: '&8[&2Splegg&8-&4OG&8] &3'
  NoPermission: '&cYou do not have permission!'
  JoinGame: '&6%player% has joined the game. &7[&e%count%/%maxcount%&7]'
  LeaveGame: '&6You have left the lobby for map &a%map%&6.'
  LobbyTimer: '&6Match starting &f%timer% &6seconds.'
  InstructionsGame: '&3Use your shovel to throw eggs and make the other players fall!'
  GraceTimeStart: '&aGrace Period (&6%grace% &aseconds)'
  GraceTimeFinish: '&6Grace Period Over!'
  EndingTimer: '&6Game is ending in &f%timer%'
  Youbrokeblocks: '&6You broke %broke% blocks.'
  KnockoutPlayer: '&6Player %player% was eliminated from the game.'
  PlayersRemaining: '&e&l%count% players remain alive.'
  AlreadyInGame: '&6You are already in a game.'
  AlreadyInLobby: '&6You are already in this lobby.'
  NoEnoughMoney: '&cERROR: You dont have enough &BDiamonds &cto purchase this shovel.!'
  NoEnoughPlayers: '&cERROR: There are not enough players to start the game.'
  NotBreakSign: '&cERROR: You cannot break a splegg sign!'
  RemovedSign: '&6Removed a splegg sign for map &c%map%&6.'
  CreateSign: '&6You have created a splegg sign for: &2%map%&6.'
  Timelimitreached: '&6Time limit reached.'
  Mapnotexist: '&cERROR: Map does not exist!'
  Mapdisabled: '&cERROR: Map is disabled.'
  Haveyoueverbought: '&cERROR: You already own this shovel.'
  BuyGoldShovel: '&BYou bought a Gold Shovel!'
  BuyDiamondShovel: '&BYou bought a Diamond Shovel!'
  VIPPrivilege: '&6Only &fOG &6players and above can enter the full game!'
  VIPJoinGame: '&6You have joined a full game thanks to your donor rank. Thank you for supporting &2True&4OG!'
Scoreboard:
  Title: '&2Splegg&r-&4OG'
  Queue: '&6Players Waiting:'
  Starting: '&6Starting in:'
  BrokenBlocks: '&eBlocks Broken:'
Money:
  KillPlayer: 0
  FinishGame: 1
Options:
  Timer: 120
  AutoStartPlayers: 4
  GraceTime: 10
Sings:
  Format:
    1: '&8[&2Splegg&r-&4OG&8]'
    2: '%status%'
    3: '%map%'
    4: '&5%count%/%maxcount%'
  Restarting:
    1: '###########################'
    2: '&8[&6Restarting &2Splegg&4OG&8]'
    3: '%map%'
    4: '###########################'
  Status:
    Join: '&4[Join]'
    Started: '&6[Started]'
    Disabled: '&4[Disabled]'
Shovels:
  Iron:
    Name: '&f&lIron Shovel'
    Lore: '&e&lRight-Click to launch eggs!'
  Gold:
    Name: '&e&lGolden Shovel'
    Lore: '&e&lRight-Click to launch eggs!'
  Diamond:
    Name: '&b&lDiamond Shovel'
    Lore: '&e&lRight-Click to launch eggs!'
GUI:
  Shop:
    Title: '&lSplegg Shop'
    Size: 10
    GoldShovel:
      Name: '&e&lGolden Shovel'
      Description: '&6Impress your SO with this fancy &eGolden Shovel&6! Price: &B%price% Diamonds&6.'
      Price: 500
    DiamondShovel:
      Name: '&b&lDiamond Shovel'
      Description: '&6The illustrious &BDiamond Shovel &6shoots TWO eggs at a time! Price: &B%price% Diamonds'
      Price: 1000
Guide:
  Item: ENCHANTED_BOOK
  Slot: 0
  Name: '&eSplegg Guide'
  Lore: '&6Learn how to play!'
Shop:
  Item: DIAMOND
  Slot: 1
  Name: '&BSplegg Shop'
  Lore: '&BBuy fancy new shovels!'
Cosmetics:
  Item: SUNFLOWER
  Slot: 4
  Name: '&3Cosmetics Menu'
  Lore: '&5Upgrade your look!'
Leave:
  Item: SLIME_BALL
  Slot: 8
  Name: '&4Leave Game'
  Lore: '&eReturn to &2True&4OG &2SMP&e!'